### ISSUE TITLE
Program can't launch due to glibc, on GNU/Linux

### ISSUE THREAD

**Issue by charlycoste** [CircuitMess/CircuitBlocks#19]
I tried to launch circuitblocks' AppImage on NixOS 20.09 but it didn't work. The standard error output gives me this :  

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.BQVBDl)
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
```

First, I thought it was owing to NixOS which is quite a special distribution so I checked it on an Ubuntu 18.04 with the AppImage binary as well but also with the .deb package file. And both two gave me the same error.

**Comment by Chuckaluphagus** [comment]
I have the identical problem, running Ubuntu 20.04.1 64-bit.  I tried the AppImage first, and when that didn't work, tried the .deb package.  Both give the same error.

```
$ circuitblocks 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.V0FhTE)
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
```

**Comment by filipbudisa** [comment]
Hello guys. The latest version of CircuitBlocks was compiled agains glibc 2.27, on Ubuntu 18.04, so that should work on both of your machines. You can find it on the releases page. Sorry for the inconvenience.
